class Section {
  String title;
  int number;
  String paragraph;
  String annotation;

  Section(this.title, this.number, this.paragraph, this.annotation);
}

final List titleList = ["General Provisions",
  "The Congress",
  "The President",
  "Flag and Seal, Seat of Government, and the States",
  "Government Organization and Employees",
  "Domestic Security",
  "Agriculture",
  "Aliens and Nationality",
  "Arbitration",
  "Armed Forces",
  "Bankruptcy",
  "Banks and Banking",
  "Census",
  "Coast Guard",
  "Commerce and Trade",
  "Conservation",
  "Copyrights",
  "Crimes and Criminal Procedure",
  "Customs Duties",
  "Education",
  "Food and Drugs",
  "Foreign Relations and Intercourse",
  "Highways",
  "Hospitals and Asylums",
  "Indians",
  "Internal Revenue Code",
  "Intoxicating Liquors",
  "Judiciary and Judicial Procedure",
  "Labor",
  "Mineral Lands and Mining",
  "Money and Finance",
  "National Guard",
  "Navigation and Navigable Waters",
  "Crime Control and Law Enforcement",
  "Patents",
  "Patriotic Societies and Observances",
  "Pay and Allowances of the Uniformed Services",
  "Veterans' Benefits",
  "Postal Service",
  "Public Buildings, Properties, and Works",
  "Public Contracts",
  "The Public Health and Welfare",
  "Public Lands",
  "Public Printing and Documents",
  "Railroads",
  "Shipping",
  "Telecommunications",
  "Territories and Insular Possessions",
  "Transportation",
  "War and National Defense",
  "National and Commercial Space Programs",
  "Voting and Elections",
  "Reserved",
  "National Park Service and Related Programs"];

final description_list = [
  "Title 1 of the United States Code outlines the general provisions of the United States Code.",
  "Title 2 of the United States Code outlines the role of Congress in the United States Code.",
  "Title 3 of the United States Code outlines the role of the President of the United States in the United States Code.",
  "Title 4 of the United States Code outlines the role of flag of the United States, Great Seal of the United States, Washington, DC, and the states in the United States Code.",
  "Title 5 of the United States Code outlines the role of government organization and employees in the United States Code.",
  "Title 6 of the United States Code is a non-positive law title of the United States Code that governs Domestic Security.",
  "Title 7 of the United States Code outlines the role of agriculture in the United States Code.",
  "Title 8 of the United States Code codifies statutes relating to aliens and nationality in the United States Code.",
  "Title 9 of the United States Code outlines the role of arbitration in the United States Code.",
  "Title 10 of the United States Code outlines the role of armed forces in the United States Code.",
  "Title 11 of the United States Code is the source of bankruptcy law in the United States Code.",
  "Title 12 of the United States Code outlines the role of Banks and Banking in the United States Code.",
  "Title 13 of the United States Code outlines the role of the United States Census in the United States Code.",
  "Title 14 of the United States Code outlines the role of the United States Coast Guard in the United States Code.",
  "Title 15 of the United States Code outlines the role of commerce and trade in the United States Code.",
  "Title 16 of the United States Code outlines the role of conservation in the United States Code.",
  "Title 17 of the United States Code is the United States Code that outlines United States copyright law.",
  "Title 18 of the United States Code is the main criminal code of the federal government of the United States.",
  "Title 19 of the United States Code outlines the role of customs and duties in the United States Code.",
  "Title 20 of the United States Code outlines the role of education in the United States Code.",
  "Title 21 of the United States Code governs Food and Drugs in the United States Code.",
  "Title 22 of the United States Code outlines the role of foreign relations and intercourse in the United States Code.",
  "Title 23 of the United States Code outlines the role of highways in the United States Code.",
  "Title 24 of the United States Code outlines the role of hospitals and psychiatric hospitals in the United States Code.",
  "Title 25 of the United States Code outlines the role of Indians in the United States Code.",
  "Title 26 of the United States Codee outlines the domestic portion of federal statutory tax law in the United States.",
  "Title 27 of the United States Code outlines the role of intoxicating liquors in the United States Code.",
  "Title 28 of the United States Code governs the federal judicial system.",
  "Title 29 of the United States Code is a code that outlines labor regulations in the United States.",
  "Title 30 of the United States Code outlines the role of mineral lands and mining in the United States Code.",
  "Title 31 of the United States Code outlines the role of the money and finance in the United States Code.",
  "Title 32 of the United States Code outlines the role of the United States National Guard in the United States Code.",
  "Title 33 of the United States Code outlines the role of navigable waters in the United States Code.",
  "Title 34 of the United States Code outlines the enforcement and control of criminal law in the United States Code.",
  "Title 35 of the United States Code outlines patent law in the United States.",
  "Title 36 of the United States Code outlines all patriotic and national observances for the United States.",
  "Title 37 of the United States Code outlines the role of Pay and Allowances of the Uniformed Services in the United States Code.",
  "Title 38 of the United States Code outlines the role of Veterans' Benefits in the United States Code.",
  "Title 39 of the United States Code outlines the role of United States Postal Service in the United States Code.",
  "Title 40 of the United States Code outlines the role of Public Buildings, Properties, and Public Works in the United States Code.",
  "Title 41 of the United States Code consists of federal statutes regarding public contracts in the United States Code.",
  "Title 42 of the United States Code is the United States Code dealing with public health, social welfare, and civil rights.",
  "Description of the title.",
  "Description of the title.",
  "Description of the title.",
  "Description of the title.",
  "Description of the title.",
  "Description of the title.",
  "Description of the title.",
  "Description of the title.",
  "Description of the title.",
  "Description of the title.",
  "Description of the title.",
  "Description of the title.",
];


final List sectionList = [
  [
    [
      [
        Section(
            "Words denoting number, gender, and so forth",
            1,
            "This is the Section's information",
            "(July 30, 1947, ch. 388, 61 Stat. 633; June 25, 1948, ch. 645, § 6, 62 Stat. 859; Oct. 31, 1951, ch. 655, § 1, 65 Stat. 710; Pub. L. 112–231, § 2(a), Dec. 28, 2012, 126 Stat. 1619.)"
        ),
        Section("\"County\" as including \"parish\", and so forth",
            2,
            "The word \"county\" includes a parish, or any other equivalent subdivision of a State or Territory of the United States.",
            "(July 30, 1947, ch. 388, 61 Stat. 633.)"),
      ],
    ],
  ]
];