class Section {
  String title;
  int number;
  String paragraph;
  String annotation;

  Section(this.title, this.number, this.paragraph, this.annotation);
}

final List titleList = ["General Provisions",
  "The Congress",
  "The President",
  "Flag and Seal, Seat of Government, and the States",
  "Government Organization and Employees",
  "Domestic Security",
  "Agriculture",
  "Aliens and Nationality",
  "Arbitration",
  "Armed Forces",
  "Bankruptcy",
  "Banks and Banking",
  "Census",
  "Coast Guard",
  "Commerce and Trade",
  "Conservation",
  "Copyrights",
  "Crimes and Criminal Procedure",
  "Customs Duties",
  "Education",
  "Food and Drugs",
  "Foreign Relations and Intercourse",
  "Highways",
  "Hospitals and Asylums",
  "Indians",
  "Internal Revenue Code",
  "Intoxicating Liquors",
  "Judiciary and Judicial Procedure",
  "Labor",
  "Mineral Lands and Mining",
  "Money and Finance",
  "National Guard",
  "Navigation and Navigable Waters",
  "Crime Control and Law Enforcement",
  "Patents",
  "Patriotic Societies and Observances",
  "Pay and Allowances of the Uniformed Services",
  "Veterans' Benefits",
  "Postal Service",
  "Public Buildings, Properties, and Works",
  "Public Contracts",
  "The Public Health and Welfare",
  "Public Lands",
  "Public Printing and Documents",
  "Railroads",
  "Shipping",
  "Telecommunications",
  "Territories and Insular Possessions",
  "Transportation",
  "War and National Defense",
  "National and Commercial Space Programs",
  "Voting and Elections",
  "Reserved",
  "National Park Service and Related Programs"];

final description_list = [
  "Title 1 of the United States Code outlines the general provisions of the United States Code.",
  "Title 2 of the United States Code outlines the role of Congress in the United States Code.",
  "Title 3 of the United States Code outlines the role of the President of the United States in the United States Code.",
  "Title 4 of the United States Code outlines the role of flag of the United States, Great Seal of the United States, Washington, DC, and the states in the United States Code.",
  "Title 5 of the United States Code outlines the role of government organization and employees in the United States Code.",
  "Description of the title.",
  "Description of the title.",
  "Description of the title.",
  "Description of the title.",
  "Description of the title.",
  "Description of the title.",
  "Description of the title.",
  "Description of the title.",
  "Description of the title.",
  "Description of the title.",
  "Description of the title.",
  "Description of the title.",
  "Description of the title.",
  "Description of the title.",
  "Description of the title.",
  "Description of the title.",
  "Description of the title.",
  "Description of the title.",
  "Description of the title.",
  "Description of the title.",
  "Description of the title.",
  "Description of the title.",
  "Description of the title.",
  "Description of the title.",
  "Description of the title.",
  "Description of the title.",
  "Description of the title.",
  "Description of the title.",
  "Description of the title.",
  "Description of the title.",
  "Description of the title.",
  "Description of the title.",
  "Description of the title.",
  "Description of the title.",
  "Description of the title.",
  "Description of the title.",
  "Description of the title.",
  "Description of the title.",
  "Description of the title.",
  "Description of the title.",
  "Description of the title.",
  "Description of the title.",
  "Description of the title.",
  "Description of the title.",
  "Description of the title.",
  "Description of the title.",
  "Description of the title.",
  "Description of the title.",
  "Description of the title.",
];


final List sectionList = [
  [
    [
      [
        Section(
            "Words denoting number, gender, and so forth",
            1,
            "This is the Section's information",
            "(July 30, 1947, ch. 388, 61 Stat. 633; June 25, 1948, ch. 645, § 6, 62 Stat. 859; Oct. 31, 1951, ch. 655, § 1, 65 Stat. 710; Pub. L. 112–231, § 2(a), Dec. 28, 2012, 126 Stat. 1619.)"
        ),
        Section("\"County\" as including \"parish\", and so forth",
            2,
            "The word \"county\" includes a parish, or any other equivalent subdivision of a State or Territory of the United States.",
            "(July 30, 1947, ch. 388, 61 Stat. 633.)"),
      ],
    ],
  ]
];